{% set version = "4.8" %}
{% set sha256 = "f79b0cfea71b37a8eeec8490db6c5f7ae7719c35587f21edb0617f370eeff633" %}

package:
  name: sed
  version: {{ version }}

source:
  fn: sed-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/sed/sed-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 1
{% endif %}
  skip: true  # [win]
  script_env:
    - BOOTSTRAPPING={{ bootstrapping }}

requirements:
  build:
    - {{ compiler('c') }}
{% if bootstrapping != 'yes' %}
    - gnuconfig  # [unix]
    - make
  host:
    - gettext >=0.19.2  # [osx]
  run:
    - gettext >=0.19.2  # [osx]
{% endif %}

test:
  commands:
    - test -f "${PREFIX}/bin/sed"
    - sed --version

about:
  home: https://www.gnu.org/software/sed/
  license: GPL-3
  license_file: COPYING
  summary: 'sed (stream editor) is a non-interactive command-line text editor.'

extra:
  recipe-maintainers:
    - tfors
